#Available tasks 
# buildgem : build the rubygem
# pkg/novedit.deb : build the Debian package

require 'app_config'
require 'date'

require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.name = $NAME
  s.version = $VERSION
  s.date = Date.today.to_s
  s.authors = $AUTHORS
  s.email = $EMAIL
  s.summary = $SUMMARY
  s.homepage = $HOMEPAGE
  s.description = $DESCRIPTION
  s.executables = ['novedit']
  s.files = FileList['*/**/*'].exclude("bacasable").exclude("features").exclude("pkg")
  s.files += FileList['*'].exclude('Rakefile')
  s.files.uniq!
  s.required_ruby_version = '>=1.8.6'
  s.add_dependency('gettext')
  s.requirements = ["GTK+ 2.16", "libglade2 for ruby ('sudo apt-get install libglade2-ruby' on Debian based systems)"]
end

Rake::GemPackageTask.new(spec) do |package|
  package.need_zip = true
  package.need_tar = true
end

#file task generated by Rake::GemPackageTask
gem_task = "pkg/" + $NAME + "-" + $VERSION + ".gem"

task :buildgem => gem_task 

file "pkg/novedit.deb" => :buildgem do |debfile|
  system "gem unpack " + gem_task
  workdir = gem_task[4..-5]
  cp "/usr/lib/ruby/1.8/setup.rb ", workdir
  """
  dch –create -v1.1.1-1
fix your email, pick a package name (libpackage-ruby is my choice), put in ‘unstable’
cd debian
put this in ‘rules’:
#!/usr/bin/make -f
# copyright 2006 by Esteban Manchado Vel�zquez

include /usr/share/cdbs/1/rules/simple-patchsys.mk
include /usr/share/cdbs/1/rules/debhelper.mk
# Ruby package with setup.rb
include /usr/share/ruby-pkg-tools/1/class/ruby-setup-rb.mk
Make a ‘control’ file like this:
Source: libtextpow-ruby
Section: libs
Priority: optional
Maintainer: Bryan McLellan
Build-Depends: cdbs, debhelper (>> 5.0.0), ruby-pkg-tools, ruby1.8
Standards-Version: 3.8.0

Package: libtextpow-ruby
Architecture: all
Depends: libtextpow-ruby1.8
Description: a library to parse and process Textmate bundles.
 .
 This is a dummy package to install the GD library bindings for
 the default version of Ruby.

Package: libtextpow-ruby1.8
Architecture: all
Depends: ruby1.8, libplist-ruby, liboniguruma-ruby
Description: a library to parse and process Textmate bundles.

Package: libtextpow-ruby-doc
Section: doc
Architecture: all
Description: a library to parse and process Textmate bundles.
 a library to parse and process Textmate bundles
 .
 This is the documentation package, with upstream documentation as well as
 generated rdoc.
On the package libpackage-ruby1.8 line, change architecture to ‘any’ if the package compiles any extensions so your package output will correctly be architecture specific. If the ruby package has no docs, pull that section out.

cd ..
dpkg-buildpackage -rfakeroot
  """
end
